name: CI

on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
    schedule:
        - cron: '42 5 * * 0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        perl: [ 'latest' ]
        dist: [ 'strawberry' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1.12.3
        with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ matrix.dist }}
      - run: perl -V
      - run: cpanm --installdeps -v -n .
      - run: cpanm -v -n .
      - run: prove -lv -r t
